# Welcome to Jekyll!
#

# Site settings
title: /dev/games
description: Conferenza Italiana sul Game Development
owner: devgames.org
first_published: 2024
email: info@devgames.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://devgames.org" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  linkedin: https://www.linkedin.com/company/devgamesconf
  #linkedin-square: https://www.linkedin.com/company/devgamesconf
  facebook-official: https://www.facebook.com/devgamesconf
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/devgamesconf/
  youtube-square: https://www.youtube.com/@devgamesconf
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
